server:
  port: 3002

spring:
  datasource:
    log:
      url: jdbc:mysql://localhost:3306/cqlog?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
      username: root
      password: 123456
      driverClassName: com.mysql.cj.jdbc.Driver
      mapperLocation: classpath:mapper/log/*.xml
      typeAliasesPackage: com.wisp.game.bet.api.dao.log.entity
      basePackage: com.wisp.game.bet.api.dao.log
    pay:
      url: jdbc:mysql://localhost:3306/cqpay?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
      username: root
      password: 123456
      driverClassName: com.mysql.cj.jdbc.Driver
      mapperLocation: classpath:mapper/pay/*.xml
      typeAliasesPackage: com.wisp.game.bet.api.dao.pay.entity
      basePackage: com.wisp.game.bet.api.dao.pay
    recharge:
      url: jdbc:mysql://localhost:3306/cq_recharge?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
      username: root
      password: 123456
      driverClassName: com.mysql.cj.jdbc.Driver
      mapperLocation: classpath:mapper/recharge/*.xml
      typeAliasesPackage: com.wisp.game.bet.recharge.dao.entity
      basePackage: com.wisp.game.bet.recharge.dao


cfg:
  playerdb_url: 127.0.0.1:27017
  playerdb_name: PlayerDB_DWC
  logdb_url: 127.0.0.1:27017
  logdb_name: LogDB_DWC
  gamedb_url: 127.0.0.1:27017
  gamedb_name: GameDB
  paydb_url: 127.0.0.1:27017
  paydb_name: PaymentDB
  configdb_url: 127.0.0.1:27017
  configdb_name: ConfigDB
  accountdb_url: 127.0.0.1:27017
  accountdb_name: AccountDB
  clouddb_url: 127.0.0.1:27017
  clouddb_name: CloudDB
  activiydb_url: 127.0.0.1:27017
  activiydb_name: CloudDB


redis:
  cache:
    host: 127.0.0.1
    port: 6379
    maxIdle: 3
    maxTotal: 10
    testOnBorrow: true