server:
  port: 40000

cfg:
  logdb_url: 127.0.0.1:27017
  logdb_name: LogDB_DWC
  configdb_url: 127.0.0.1:27017
  configdb_name: ConfigDB
  accountdb_url: 127.0.0.1:27017
  accountdb_name: AccountDB
  paydb_url: 127.0.0.1:27017
  paydb_name: PaymentDB
  playerdb_url: 127.0.0.1:27017
  playerdb_name: PlayerDB_DWC

